"use client";

import { use, useState } from "react";
import { IncidentTable } from "../../../../components/incidents/IncidentTable";
import { EmptyState } from "../../../../components/shared/EmptyState";
import { useIncidents } from "../../../../hooks/useIncidents";
import type { IncidentSeverity, IncidentStatus } from "../../../../types/incident";

export default function IncidentsPage({ params }: { params: Promise<{ id: string }> }) { const { id } = use(params); const [status, setStatus] = useState<IncidentStatus | undefined>(); const [severity, setSeverity] = useState<IncidentSeverity | undefined>(); const { items, loading, error } = useIncidents(id, { status, severity }); return <main className="p-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-semibold text-[#102522]">Incidents</h1><p className="mt-2 text-sm text-slate-500">Investigate failures across this project.</p></div><div className="flex gap-2"><select value={status ?? ""} onChange={(event) => setStatus((event.target.value || undefined) as IncidentStatus | undefined)} className="rounded-md border border-teal-100 bg-white px-3 py-2 text-sm"><option value="">All statuses</option><option value="open">Open</option><option value="acknowledged">Acknowledged</option><option value="resolved">Resolved</option></select><select value={severity ?? ""} onChange={(event) => setSeverity((event.target.value || undefined) as IncidentSeverity | undefined)} className="rounded-md border border-teal-100 bg-white px-3 py-2 text-sm"><option value="">All severity</option><option value="critical">Critical</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></div></div>{error && <p className="mt-6 rounded-md bg-rose-50 p-4 text-sm text-rose-700">{error.message}</p>}{loading ? <p className="mt-8 text-sm text-slate-500">Loading incidents...</p> : items.length ? <div className="mt-8"><IncidentTable projectId={id} incidents={items} /></div> : <div className="mt-8"><EmptyState title="No incidents found" message="Try changing the filters." /></div>}</main>; }

